# Generated by Django 4.0 on 2024-07-25 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoGasolina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embarcacion', models.IntegerField()),
                ('consumo_gasolina', models.DecimalField(decimal_places=2, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='CostoGalonAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='CostoGalonB_05',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='CostoGalonHielo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='CostoTipoCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='CostoTripulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_basico', models.DecimalField(decimal_places=2, max_digits=9)),
                ('participacion', models.DecimalField(decimal_places=2, max_digits=9)),
                ('bonificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('total_participacion', models.DecimalField(decimal_places=2, max_digits=9)),
                ('aporte_REP', models.DecimalField(decimal_places=2, max_digits=9)),
                ('gratificacion', models.DecimalField(decimal_places=2, max_digits=9)),
                ('vacaciones', models.DecimalField(decimal_places=2, max_digits=9)),
                ('CTS', models.DecimalField(decimal_places=2, max_digits=9)),
                ('ESSALUD', models.DecimalField(decimal_places=2, max_digits=9)),
                ('SENATI', models.DecimalField(decimal_places=2, max_digits=9)),
                ('SCTR_SAL', models.DecimalField(decimal_places=2, max_digits=9)),
                ('SCTR_PEN', models.DecimalField(decimal_places=2, max_digits=9)),
                ('poliza_seguro', models.DecimalField(decimal_places=2, max_digits=9)),
                ('total_CT', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='DerechoPesca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='DiarioDePesca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embarcacion', models.IntegerField()),
                ('especie', models.IntegerField()),
                ('fecha', models.DateField()),
                ('numero_alcance', models.IntegerField()),
                ('zona_pesca', models.CharField(max_length=255)),
                ('estrato', models.CharField(max_length=255)),
                ('profundidad', models.IntegerField()),
                ('tiempo_efectivo', models.TimeField()),
                ('rango_talla_inicial', models.IntegerField()),
                ('rango_talla_final', models.IntegerField()),
                ('moda', models.IntegerField()),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ar', models.IntegerField()),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Embarcaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('costo_zarpe', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Especies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('precio', models.IntegerField()),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MecanismosI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('costo_dia', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='TarifasCostos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_t', models.CharField(max_length=255)),
                ('tarifa', models.DecimalField(decimal_places=4, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='ZonaPesca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Viveres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_zarpe', models.DecimalField(decimal_places=2, max_digits=5)),
                ('embarcacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.embarcaciones')),
            ],
        ),
        migrations.CreateModel(
            name='FlotaDP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_cambio', models.DecimalField(decimal_places=2, max_digits=9)),
                ('horas_faena', models.CharField(max_length=255)),
                ('kilos_declarados', models.DecimalField(decimal_places=2, max_digits=9)),
                ('merluza', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('bereche', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('volador', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('merluza_descarte', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('otro', models.CharField(blank=True, max_length=255, null=True)),
                ('kilo_otro', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('toneladas_procesadas', models.DecimalField(decimal_places=2, max_digits=9)),
                ('toneladas_recibidas', models.DecimalField(decimal_places=2, max_digits=9)),
                ('total_tripulacion', models.DecimalField(decimal_places=2, max_digits=9)),
                ('consumo_gasolina', models.DecimalField(decimal_places=2, max_digits=9)),
                ('total_gasolina', models.DecimalField(decimal_places=2, max_digits=9)),
                ('consumo_hielo', models.DecimalField(decimal_places=2, max_digits=9)),
                ('total_hielo', models.DecimalField(decimal_places=2, max_digits=9)),
                ('consumo_agua', models.DecimalField(decimal_places=2, max_digits=9)),
                ('total_agua', models.DecimalField(decimal_places=2, max_digits=9)),
                ('consumo_viveres', models.DecimalField(decimal_places=2, max_digits=9)),
                ('total_vivieres', models.DecimalField(decimal_places=2, max_digits=9)),
                ('dias_inspeccion', models.DecimalField(decimal_places=2, max_digits=9)),
                ('total_servicio_inspeccion', models.DecimalField(decimal_places=2, max_digits=9)),
                ('total_derecho_pesca', models.DecimalField(decimal_places=2, max_digits=9)),
                ('total_costo', models.DecimalField(decimal_places=2, max_digits=9)),
                ('costo_tm_captura', models.DecimalField(decimal_places=2, max_digits=9)),
                ('csot', models.DecimalField(decimal_places=2, max_digits=9)),
                ('embarcacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.embarcaciones')),
                ('zona_pesca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.zonapesca')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('idgeneral', models.CharField(blank=True, max_length=50, null=True)),
                ('nombrey_apellido', models.CharField(max_length=100)),
                ('jefe_inmediato', models.CharField(blank=True, max_length=100, null=True)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_usurio', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
