# Generated by Django 4.0 on 2024-08-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especies',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
