# Generated by Django 4.0 on 2024-07-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_flotadp_costo_basico_flotadp_participacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='embarcaciones',
            name='bonificacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
