# Generated by Django 4.0 on 2024-08-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_especies_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embarcaciones',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
