# Generated by Django 4.0 on 2024-08-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_embarcaciones_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flotadp',
            name='costo_agua',
            field=models.DecimalField(decimal_places=3, max_digits=11),
        ),
        migrations.AlterField(
            model_name='flotadp',
            name='costo_gasolina',
            field=models.DecimalField(decimal_places=3, max_digits=11),
        ),
        migrations.AlterField(
            model_name='flotadp',
            name='costo_hilo',
            field=models.DecimalField(decimal_places=3, max_digits=11),
        ),
        migrations.AlterField(
            model_name='flotadp',
            name='tipo_cambio',
            field=models.DecimalField(decimal_places=3, max_digits=11),
        ),
        migrations.AlterField(
            model_name='flotadp',
            name='total_agua',
            field=models.DecimalField(decimal_places=3, max_digits=11),
        ),
        migrations.AlterField(
            model_name='flotadp',
            name='total_gasolina',
            field=models.DecimalField(decimal_places=3, max_digits=11),
        ),
        migrations.AlterField(
            model_name='flotadp',
            name='total_hielo',
            field=models.DecimalField(decimal_places=3, max_digits=11),
        ),
    ]
