# Generated by Django 4.0 on 2024-07-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_embarcaciones_bonificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embarcaciones',
            name='bonificacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
