# Generated by Django 4.0 on 2024-07-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_embarcaciones_bonificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='flotadp',
            name='bonificacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
