# Generated by Django 4.0 on 2024-08-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_flotadp_costo_agua_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diariodepesca',
            name='tiempo_efectivo',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
