# Generated by Django 4.0 on 2024-07-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_flotadp_bonificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='embarcaciones',
            name='boner',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
