# Generated by Django 4.0 on 2024-08-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_diariodepesca_tiempo_efectivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='flotadp',
            name='costo_cap_x_dolar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
            preserve_default=False,
        ),
    ]
