# Generated by Django 4.0 on 2024-07-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_embarcaciones_boner'),
    ]

    operations = [
        migrations.AddField(
            model_name='flotadp',
            name='total_participacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
