# Generated by Django 4.0 on 2024-08-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_flotadp_costo_cap_x_dolar'),
    ]

    operations = [
        migrations.AddField(
            model_name='diariodepesca',
            name='p_flota_dolares',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diariodepesca',
            name='precio_lances',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diariodepesca',
            name='t_flota',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
            preserve_default=False,
        ),
    ]
