# Generated by Django 4.0 on 2024-07-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_flotadp_total_participacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='flotadp',
            name='aporte_REP',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
