# Generated by Django 4.0 on 2024-07-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_flotadp_aporte_rep'),
    ]

    operations = [
        migrations.AddField(
            model_name='flotadp',
            name='gratificacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
