# Generated by Django 4.0 on 2024-07-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_flotadp_essalud'),
    ]

    operations = [
        migrations.AddField(
            model_name='flotadp',
            name='senati',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
