# Generated by Django 4.0 on 2024-07-31 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_flotadp_poliza_seguro'),
    ]

    operations = [
        migrations.AddField(
            model_name='diariodepesca',
            name='flotaDP',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.flotadp'),
            preserve_default=False,
        ),
    ]
