# Generated by Django 4.0 on 2024-07-31 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_diariodepesca_flotadp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diariodepesca',
            old_name='flotaDP',
            new_name='flotaDP_id',
        ),
    ]
