# Generated by Django 4.0 on 2024-07-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_rename_flotadp_diariodepesca_flotadp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='flotadp',
            name='galon_hora',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
