# Generated by Django 4.0 on 2024-07-31 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_flotadp_galon_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='flotadp',
            name='precio_otro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
