# Generated by Django 4.0 on 2024-07-31 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_flotadp_precio_otro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diariodepesca',
            name='zona_pesca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.zonapesca'),
        ),
    ]
