# Generated by Django 4.0 on 2024-08-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_alter_diariodepesca_porcentaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costogalonagua',
            name='costo',
            field=models.DecimalField(decimal_places=3, max_digits=11),
        ),
        migrations.AlterField(
            model_name='costogalonb_05',
            name='costo',
            field=models.DecimalField(decimal_places=3, max_digits=11),
        ),
        migrations.AlterField(
            model_name='costogalonhielo',
            name='costo',
            field=models.DecimalField(decimal_places=3, max_digits=11),
        ),
        migrations.AlterField(
            model_name='costotipocambio',
            name='costo',
            field=models.DecimalField(decimal_places=3, max_digits=11),
        ),
    ]
