# Generated by Django 4.0 on 2024-08-04 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_alter_costogalonagua_costo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flotadp',
            name='precio_bereche',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='flotadp',
            name='precio_merluza',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='flotadp',
            name='precio_merluzaNP',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='flotadp',
            name='precio_volador',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
