# Generated by Django 4.0 on 2024-08-10 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_flotadp_costo_agua_flotadp_costo_gasolina_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flotadp',
            name='bereche',
        ),
        migrations.RemoveField(
            model_name='flotadp',
            name='merluza',
        ),
        migrations.RemoveField(
            model_name='flotadp',
            name='merluza_descarte',
        ),
        migrations.RemoveField(
            model_name='flotadp',
            name='precio_bereche',
        ),
        migrations.RemoveField(
            model_name='flotadp',
            name='precio_merluza',
        ),
        migrations.RemoveField(
            model_name='flotadp',
            name='precio_merluzaNP',
        ),
        migrations.RemoveField(
            model_name='flotadp',
            name='precio_volador',
        ),
        migrations.RemoveField(
            model_name='flotadp',
            name='volador',
        ),
        migrations.AddField(
            model_name='flotadp',
            name='especie',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flotadp',
            name='precio_especie',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
