# Generated by Django 4.0 on 2024-08-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_remove_flotadp_bereche_remove_flotadp_merluza_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flotadp',
            name='precio_especie',
        ),
        migrations.AlterField(
            model_name='flotadp',
            name='especie',
            field=models.JSONField(),
        ),
    ]
