# Generated by Django 4.0 on 2024-08-13 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_remove_flotadp_precio_especie_alter_flotadp_especie'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToneladasProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(blank=True, max_length=8, null=True)),
                ('fecha', models.DateField()),
                ('toneladas_procesables', models.DecimalField(decimal_places=2, max_digits=9)),
                ('toneladas_procesadas', models.DecimalField(decimal_places=2, max_digits=9)),
                ('toneladas_NP', models.DecimalField(decimal_places=2, max_digits=9)),
                ('embarcacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.embarcaciones')),
                ('zona_pesca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.zonapesca')),
            ],
        ),
    ]
