# Generated by Django 4.0 on 2024-08-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_toneladasproduccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='flotadp',
            name='toneladas_NP',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='flotadp',
            name='toneladas_procesadas_produccion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
