# Generated by Django 4.0 on 2024-08-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_flotadp_toneladas_np_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='jefe_inmediato',
        ),
        migrations.AddField(
            model_name='customuser',
            name='imagen_usuario',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tipo_usurio',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('Embarcaciones', 'Embarcaciones'), ('Proceso', 'Proceso')], max_length=50),
        ),
    ]
